Repository ron010-1/quizJS, pull requests merged in 2024-08, with the labels that each got.

#1 adição do arquivo JSON
  index.html
  questions.js
  scripts.js
  styles.css
Labels: enhancement

#2 Novas funções básicas do quiz e estilização da página
  index.html
  questions.json
  scripts.js
  styles.css
Labels: bug, enhancement

#3 view: mudando estilização
  index.html
  scripts.js
  styles.css
Labels: enhancement, good first issue

#4 Acerto, erro e passar pra proxia questao
  index.html
  scripts.js
  styles.css
Labels: enhancement, good first issue

#6 Conserto do bug ao reiniciar o jogo
  index.html
  scripts.js
Labels: bug

#8 Fazendo a finalização do quiz
  index.html
  scripts.js
Labels: enhancement, good first issue

#10 Quiz gerado apenas uma vez por dia
  scripts.js
Labels: enhancement, good first issue
